"""Init UUID schema

Revision ID: 2d6769b1fea1
Revises: 
Create Date: 2026-04-15 13:53:11.310086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d6769b1fea1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('master_password_hash', sa.String(length=64), nullable=True),
    sa.Column('auth_salt', sa.String(length=64), nullable=True),
    sa.Column('role', sa.Enum('premium', 'default', name='userrole'), nullable=False),
    sa.Column('zero_knowledge_accepted', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('vault_items',
    sa.Column('vaultitem_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('e_title', sa.String(), nullable=False),
    sa.Column('e_url', sa.String(), nullable=True),
    sa.Column('e_username', sa.String(), nullable=True),
    sa.Column('e_password', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('vaultitem_id')
    )
    op.create_index(op.f('ix_vault_items_user_id'), 'vault_items', ['user_id'], unique=False)
    op.create_index(op.f('ix_vault_items_vaultitem_id'), 'vault_items', ['vaultitem_id'], unique=False)
    op.create_table('custom_fields',
    sa.Column('customfield_id', sa.UUID(), nullable=False),
    sa.Column('vaultitem_id', sa.UUID(), nullable=False),
    sa.Column('e_key', sa.String(), nullable=False),
    sa.Column('e_value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['vaultitem_id'], ['vault_items.vaultitem_id'], ),
    sa.PrimaryKeyConstraint('customfield_id')
    )
    op.create_index(op.f('ix_custom_fields_customfield_id'), 'custom_fields', ['customfield_id'], unique=False)
    op.create_index(op.f('ix_custom_fields_vaultitem_id'), 'custom_fields', ['vaultitem_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_custom_fields_vaultitem_id'), table_name='custom_fields')
    op.drop_index(op.f('ix_custom_fields_customfield_id'), table_name='custom_fields')
    op.drop_table('custom_fields')
    op.drop_index(op.f('ix_vault_items_vaultitem_id'), table_name='vault_items')
    op.drop_index(op.f('ix_vault_items_user_id'), table_name='vault_items')
    op.drop_table('vault_items')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
